// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
  "/wipe": {
    params: {};
  };
  "/builder": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/resume/:id" | "/wipe" | "/builder";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.jsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.jsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/resume.jsx": {
    id: "routes/resume";
    page: "/resume/:id";
  };
  "routes/wipe.jsx": {
    id: "routes/wipe";
    page: "/wipe";
  };
  "routes/builder.jsx": {
    id: "routes/builder";
    page: "/builder";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/auth": typeof import("./app/routes/auth.jsx");
  "routes/upload": typeof import("./app/routes/upload.jsx");
  "routes/resume": typeof import("./app/routes/resume.jsx");
  "routes/wipe": typeof import("./app/routes/wipe.jsx");
  "routes/builder": typeof import("./app/routes/builder.jsx");
};